#!/bin/sh

# GNUSTEP_MSYS=${MSYSTEM,,}/../

export CC=gcc
export CXX=g++

MSYS_ROOT=/ 
USR_ROOT=${MSYS_ROOT}usr
GNUSTEP_ROOT=${USR_ROOT}/GNUstep

# echo "Copying patched shlwapi.h header"
# cp ./tools-scripts/Patched/shlwapi.h /mingw64/x86_64-w64-mingw32/include/shlwapi.h

echo "** Installation directory is $GNUSTEP_ROOT"
echo "** Building GNUstep for MSYS64 + gcc on Windows"
echo ""

export PKG_CONFIG_PATH=${USR_ROOT}/local/lib/pkgconfig:${USR_ROOT}/lib/pkgconfig:${PKG_CONFIG_PATH}

# Build make
echo ""
echo "############## Build tools-make"
cd tools-make
make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM distclean
./configure --with-library-combo=gnu-gnu-gnu --with-layout=gnustep --prefix=${GNUSTEP_ROOT} --enable-install-ld-so-conf && make install messages=yes
source ${GNUSTEP_ROOT}/System/Library/Makefiles/GNUstep.sh

# Build base
echo ""
echo "############## Build libs-base"
cd ../libs-base
make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM distclean
CFLAGS+=-I/usr/local/include LDFLAGS+=-L/usr/local/lib ./configure --with-installation-domain=SYSTEM --disable-libdispatch --disable-icu --without-unwind && make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install messages=no -j4

# Build gui
echo ""
echo "############## Build libs-gui"
cd ../libs-gui
make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM distclean
./configure && make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install messages=no -j4

# Build backend
echo ""
echo "############## Build libs-back"
cd ../libs-back
make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM distclean
./configure --enable-graphics=cairo && make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install messages=no -j4

# Set default backend
# defaults write NSGlobalDomain GSBackend libgnustep-cairo

echo ""
echo "** Done."

exit 0