#!/bin/bash

libs_files="libs-xcode"
tools_files="tools-buildtool"
apps_files="apps-gorm plugins-themes-WinUXTheme"
CPUS=`nproc`
OS=`uname -s`


build_and_install()
{
    echo "***** Building ${1}..."
    cd ${1}
    if [ -f configure ]; then
	./configure
    fi
    if [ -f GNUmakefile ]; then
	make -j${CPUS} debug=yes
	if [ "$OS" == "Linux" ]; then
	    sudo -- sh -c '. /usr/GNUstep/System/Library/Makefiles/GNUstep.sh && make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install'
	else
	    . /usr/GNUstep/System/Library/Makefiles/GNUstep.sh && make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install
        fi  
    fi
    cd ..
    echo "***** Done"
}

. /usr/GNUstep/System/Library/Makefiles/GNUstep.sh

echo "======= Building libraries."
for file in ${libs_files}
do
    build_and_install $file
done

echo "======= Building tools."
for file in ${tools_files}
do
    build_and_install $file
done

echo "======= Building applications."
for file in ${apps_files}
do
    build_and_install $file
done

exit 0
