#!/bin/sh

export CC=egcc
export CXX=eg++
export LD=ld.bfd
export MAKE=gmake
export SUDO=sudo
# export CFLAGS=-I/usr/local/include/gnustep
# export LDFLAGS=-L/usr/local/lib

ROOT=/ 
USR_ROOT=${ROOT}usr
GNUSTEP_ROOT=${USR_ROOT}/GNUstep
export GNUSTEP_CONFIG_FILE=/etc/GNUstep/GNUstep.conf
export GNUSTEP_INSTALL_LD_SO_CONF=no
export prefix=${GNUSTEP_ROOT}

echo ""
echo "Installation directory is $GNUSTEP_ROOT"
echo "Building GNUstep for OpenBSD"
echo ""

CPUS=4
SUDO='sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH'
# KERNEL=`uname -s | awk '{print tolower($0)}'`
scriptsdir="`pwd`/tools-scripts"

# Build make
cd tools-make
make clean
./configure --with-layout=gnustep CC=${CC} CXX=${CXX} LD=${LD} --prefix=${prefix}
echo "======== Build make"
${MAKE}
${SUDO} -u root ${MAKE} install
. ${GNUSTEP_ROOT}/System/Library/Makefiles/GNUstep.sh

# Build base
echo "======== Build base"
cd ../libs-base
./configure --with-installation-domain=SYSTEM
${MAKE} debug=yes messages=no -j4
${SUDO} -u root ./install.sh ${GNUSTEP_ROOT} ${MAKE}
echo "==="

# Build gui
echo "======== Build gui"
cd ../libs-gui
./configure
LDFLAGS=${LDFLAGS} CC=${CC} CXX=${CXX} ${MAKE} debug=yes messages=no -j4
${SUDO} -u root ./install.sh ${GNUSTEP_ROOT} ${MAKE}
echo "==="

# Build backend
echo "======== Build back"
cd ../libs-back
./configure --enable-graphics=cairo
LDFLAGS=${LDFLAGS} CC=${CC} CXX=${CXX} ${MAKE} debug=yes messages=no -j4
${SUDO} -u root ./install.sh ${GNUSTEP_ROOT} ${MAKE}
echo "==="

# Set default backend
# defaults write NSGlobalDomain GSBackend libgnustep-cairo

echo "Done."

exit 0
