#!/bin/sh

# Libraries/Apps/Tools
libs_files="libs-xcode libs-ppd libs-steptalk libs-ucsdata libs-renaissance apps-gorm libs-gdl2 libs-gsweb libs-java"
tools_files="tools-charsets"
apps_files="apps-systempreferences apps-gworkspace apps-projectcenter apps-thematic apps-easydiff"

# OS
OS=`uname -s`

# OpenBSD?
# number of processes
if [ "$OS" == "OpenBSD" ]; then
   CPUS=`sysctl hw.ncpu | sed 's/hw.ncpu\=//g'`
   MAKE="gmake"
else
   CPUS=`nproc`
   MAKE="make"
fi

# func..
build_and_install()
{
    echo "***** Building ${1}..."
    cd ${1}
    if [ -f configure ]; then
	./configure
    fi
    if [ -f GNUmakefile ]; then
	$MAKE -j${CPUS} debug=yes
	if [ "$OS" == *"MINGW64_NT"* ]; then
	    . /usr/GNUstep/System/Library/Makefiles/GNUstep.sh && $MAKE GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install
	else
	    if [ "$OS" == "OpenBSD" ]; then
	       sudo -- sh -c '. /usr/GNUstep/System/Library/Makefiles/GNUstep.sh && gmake GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install'
	    else
	       sudo -- sh -c '. /usr/GNUstep/System/Library/Makefiles/GNUstep.sh && make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install'
	    fi
        fi  
    fi
    cd ..
    echo "***** Done"
    echo " "
}

install_files()
{
    for file in ${1}
    do
	build_and_install $file
    done
}

do_install()
{
    . /usr/GNUstep/System/Library/Makefiles/GNUstep.sh

    echo "======= Building libraries."
    install_files "${libs_files}"

    echo "======= Building tools."
    install_files "${tools_files}"

    echo "======= Building applications."
    install_files "${apps_files}"
}

do_install
exit 0
