#!/bin/sh

CLANG=${1:-clang}
CLANGPP=${2:-clang++}

SUDO='sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH'
CPUS="1"
ARCH=`uname -m`

cd /tmp

# pre-create some directories
${SUDO} mkdir -p /usr/GNUstep/Local/Library/Libraries
${SUDO} mkdir -p /usr/GNUstep/Local/Library/Headers

# cleanup
sudo rm -rf /tmp/libdispatch
sudo rm -rf /tmp/libobjc2

# pull
git clone --recursive https://github.com/gnustep/libobjc2.git

# set vars
export CC=${CLANG}
export CXX=${CLANGPP}

# build and install
echo "======== Installing libobjc2..."
cd /tmp/libobjc2
mkdir build
cd build
cmake -DGNUSTEP_INSTALL_TYPE=LOCAL ../
make -j${CPUS}
${SUDO} -E make install && ${SUDO} ldconfig

if [ $ARCH != arm7l ]; then
git clone https://github.com/apple/swift-corelibs-libdispatch.git libdispatch
echo "======== Installing libdispatch..."
cd /tmp/libdispatch
rm -rf build
mkdir build
cd build
cmake ../
make -j${CPUS}
${SUDO} -E make install && ${SUDO} ldconfig
fi

echo "Done."
