#!/bin/sh

CLANG=${1:-clang}
CLANGPP=${2:-clang++}

SUDO='sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH'
CPUS="1"

cd /tmp

# pre-create some directories
${SUDO} mkdir -p /usr/GNUstep/Local/Library/Libraries
${SUDO} mkdir -p /usr/GNUstep/Local/Library/Headers

# cleanup
rm -rf /tmp/libdispatch
rm -rf /tmp/libpwq
rm -rf /tmp/libkqueue
rm -rf /tmp/libobjc2
   
# pull
git clone --recursive https://github.com/gnustep/libobjc2.git
git clone https://github.com/mheily/libpwq.git
# git clone https://github.com/mheily/libkqueue.git
git clone https://github.com/nickhutchinson/libdispatch.git

# set vars
export CC=${CLANG}
export CXX=${CLANGPP}

# build and install
echo "======== Installing libobjc2..."
cd /tmp/libobjc2
mkdir build
cd build
cmake -DGNUSTEP_INSTALL_TYPE=LOCAL ../
make -j${CPUS}
${SUDO} -E make install
if [ $? == 0 ]; then
  ${SUDO} ldconfig
fi

echo "======== Installing libpwq..."
cd /tmp/libpwq
mkdir build
cd build
cmake ../
make -j${CPUS}
${SUDO} -E make install
if [ $? == 0 ]; then
  ${SUDO} ldconfig
fi

# echo "======== Installing libkqueue..."
# cd /tmp/libkqueue
# mkdir build
# cd build
# cmake ../
# make -j${CPUS}
# ${SUDO} -E make install
# if [ $? == 0 ]; then
#   ${SUDO} ldconfig
# fi

echo "======== Installing libdispatch..."
cd /tmp/libdispatch
rm -rf build
mkdir build
cd build
../configure
make -j${CPUS}
${SUDO} make install
if [ $? == 0 ]; then
  ${SUDO} ldconfig
fi

echo "Done."

