#!/bin/sh

PATH=/usr/local/bin:${PATH}
export PATH

REVISION=$1

# Create development...
if [ -e ~/Development ]
then
    cd ~/Development
else
    mkdir ~/Development
fi

# Update llvm...
cd ~/Development
rm -rf llvm-project
git clone https://github.com/llvm/llvm-project.git
cd llvm-project

# Make the build directory...
cd ~/Development
rm -rf build
mkdir -p build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/opt/local -DLLVM_ENABLE_PROJECTS=clang -DLLVM_USE_LINKER=gold -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../llvm-project/llvm
cmake --build .

