#!/bin/sh

PREFIX="https://github.com/gnustep/"
FILES="tools-make libs-back libs-gui libobjc2 libs-base libs-corebase plugins-themes-WinUXTheme tools-scripts libs-xcode apps-gorm plugins-session"

for file in ${FILES}
do
    GITURL=${PREFIX}${file}
    if
	test -d ${file}
    then
        cd $file
        git pull ${GITURL} master
	cd ..
    else
	git clone --recursive ${GITURL}
    fi
done

exit 0
