#!/bin/sh

CLASSNAME=$1
SUPERCLASS=$2
VERSION=$3
USERNAME=$4
DATE=`date +"%d-%m-%Y"`
CDATE=`date +"%Y"`

# Superclass
if [ -z "$SUPERCLASS" ]
then
    SUPERCLASS=NSObject
fi

# Version
if [ -z "$VERSION" ]
then
    VERSION=10_0
fi

# Username
if [ -z "$USERNAME" ]
then
    UNAME=`whoami`
    USERNAME=`getent passwd ${UNAME} | cut -d ':' -f 5 | cut -d ',' -f 1`
fi

# if no class, show usage
if [ -z "$CLASSNAME" ]
then
    echo "Usage: CLASSNAME SUPERCLASS VERSION USERNAME"
    exit 0
else
    echo "Creating class ${CLASSNAME}."
fi

# Build the template...
if [ "${SUPERCLASS}" = "NSObject" ]; then
cat << !EOF > ${CLASSNAME}.h
/* Definition of class ${CLASSNAME}
   Copyright (C) ${CDATE} Free Software Foundation, Inc.
   
   By: ${USERNAME}
   Date: ${DATE}

   This file is part of GNUstep.
   
   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.
   
   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.
   
   You should have received a copy of the GNU Lesser General Public
   License along with this library; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110 USA.
*/

#ifndef _${CLASSNAME}_h_INCLUDE
#define _${CLASSNAME}_h_INCLUDE

#import <Foundation/${SUPERCLASS}.h>
#import <GNUstepBase/GSVersionMacros.h>

#if	defined(__cplusplus)
extern "C" {
#endif

GS_EXPORT_CLASS
@interface ${CLASSNAME} : ${SUPERCLASS}

@end

#if	defined(__cplusplus)
}
#endif

#endif	/* _${CLASSNAME}_h_INCLUDE */

!EOF

else
					   
cat << !EOF > ${CLASSNAME}.h
/* Definition of class ${CLASSNAME}
   Copyright (C) ${CDATE} Free Software Foundation, Inc.
   
   By: ${USERNAME}
   Date: ${DATE}

   This file is part of GNUstep.
   
   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.
   
   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.
   
   You should have received a copy of the GNU Lesser General Public
   License along with this library; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110 USA.
*/

#ifndef _${CLASSNAME}_h_INCLUDE
#define _${CLASSNAME}_h_INCLUDE

#import "${SUPERCLASS}.h"
#import <GNUstepBase/GSVersionMacros.h>

#if	defined(__cplusplus)
extern "C" {
#endif

GS_EXPORT_CLASS
@interface ${CLASSNAME} : ${SUPERCLASS}

@end

#if	defined(__cplusplus)
}
#endif

#endif	/* _${CLASSNAME}_h_INCLUDE */

!EOF
fi
				       
cat << !EOF2 > ${CLASSNAME}.m
/* Implementation of class ${CLASSNAME}
   Copyright (C) ${CDATE} Free Software Foundation, Inc.
   
   By: ${USERNAME}
   Date: ${DATE}

   This file is part of GNUstep.
   
   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.
   
   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.
   
   You should have received a copy of the GNU Lesser General Public
   License along with this library; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110 USA.
*/

#import "${CLASSNAME}.h"

@implementation ${CLASSNAME}

@end

!EOF2

					   
