#!/bin/sh

CLASSNAME=$1
SUPERCLASS=$2
USERNAME=$3
VERSION=$4
DATE=`date`

# Superclass
if [ -z "$SUPERCLASS" ]
then
        SUPERCLASS=NSObject
fi

# Version
if [ -z "$VERSION" ]
then
        VERSION=10_0
fi

# Username
if [ -z "$USERNAME" ]
then
        USERNAME=`whoami`
fi

# if no class, show usage
if [ -z "$CLASSNAME" ]
then
        echo "Usage: CLASSNAME SUPERCLASS USERNAME VERSION"
        exit 0
else
        echo "Creating class ${CLASSNAME}."
fi

# Build the template...
cd libs-base/Headers/Foundation
cat << !EOF > ${CLASSNAME}.h
/* Definition of class ${CLASSNAME}
   Copyright (C) 2019 Free Software Foundation, Inc.
   
   By: ${USERNAME}
   Date: ${DATE}

   This file is part of the GNUstep Library.
   
   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2 of the License, or (at your option) any later version.
   
   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.
   
   You should have received a copy of the GNU Lesser General Public
   License along with this library; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02111 USA.
*/

#ifndef _${CLASSNAME}_h_GNUSTEP_BASE_INCLUDE
#define _${CLASSNAME}_h_GNUSTEP_BASE_INCLUDE

#import <Foundation/${SUPERCLASS}.h>

#if OS_API_VERSION(MAC_OS_X_VERSION_${VERSION}, GS_API_LATEST)

#if	defined(__cplusplus)
extern "C" {
#endif

@interface ${CLASSNAME} : ${SUPERCLASS}

@end

#if	defined(__cplusplus)
}
#endif

#endif	/* GS_API_MACOSX */

#endif	/* _${CLASSNAME}_h_GNUSTEP_BASE_INCLUDE */

!EOF

cd ../../Source
cat << !EOF2 > ${CLASSNAME}.m
/* Implementation of class ${CLASSNAME}
   Copyright (C) 2019 Free Software Foundation, Inc.
   
   By: ${USERNAME}
   Date: ${DATE}

   This file is part of the GNUstep Library.
   
   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2 of the License, or (at your option) any later version.
   
   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.
   
   You should have received a copy of the GNU Lesser General Public
   License along with this library; if not, write to the Free
   Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02111 USA.
*/

#import <Foundation/${CLASSNAME}.h>

@implementation ${CLASSNAME}

@end

!EOF2
