#!/bin/sh

mkdir -p gnustep
cd gnustep
git clone https://github.com/gnustep/tools-scripts
./tools-scripts/clone-app-repos-https

echo "\n================ Install Dependencies ================"
# Install dependencies
./tools-scripts/install-dependencies-linux

echo "\n================ Build ================"
# Build it...
./tools-scripts/update-gnustep clang

