#!/bin/sh

echo "Install GNUstep"
echo " "
cat <<EOF
                    @@@@@@@@@                     
               @@@@@@@@@@@@@@@@@@@                
            @@@@@@@@@@@@@@@@@@@@@@@@@             
          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@          
         @@@@@@@@@@@@@@@@@@@@@@@         @@@@@    
       @@@@@@@@@@@@@@@@@@@@@@@@@          @@@@    
      @@@@@@@@@@@@@@@@@@@@@@@@@@           @@@    
     @@@@@@@@@@@@@@@@@@@@@@@@@@@            @@    
     @@@@@@@@@@@@@@@@@@@@@@@@@@@             @    
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@             @    
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@                  
    @@@@@@@@@@@@@@                                
    @@@@@@@@@@@@@@                                
     @@@@@@@@@@@@@                           @    
     @@@@@@@@@@@@@                           @    
      @@@@@@@@@@@@                          @@    
      @@@@@@@@@@@@                         @@@    
       @@@@@@@@@@@                        @@@@    
         @@@@@@@@@                       @@@@@    
    @@@@@@@                            @@@@@@@    
    @@@@@@@@@                        @@@@@@@@@    
    @@@@@@@@@@@@                  @@@@@@@@@@@@    
    @@@@@@@@@@@@@@@@@@      @@@@@@@@@@@@@@@@@@    
EOF

echo " "
echo "IMPORTANT!"
echo "You must update your .ssh directory so it contains your github ssh key"
echo " "
export KERNEL=`uname -s | sed "s/\-.*//g" | awk '{print(tolower($0))}'`
echo "Begin setup for ${KERNEL}"

export USER=`whoami`
if [ "X${KERNEL}" == "Xopenbsd" ];then
  ftp -o ./setup-${KERNEL} https://raw.githubusercontent.com/gnustep/tools-scripts/master/setup-${KERNEL}
else
  curl -fsSL > ./setup-${KERNEL} https://raw.githubusercontent.com/gnustep/tools-scripts/master/setup-${KERNEL}
fi

./setup-${KERNEL}
rm ./setup-${KERNEL}

echo "======== Create gnustep build directories ========"
mkdir -p gnustep
cd gnustep
git clone git@github.com:gnustep/tools-scripts.git
./tools-scripts/clone-all-repos

echo "================ Install Dependencies ================"
# Install dependencies
./tools-scripts/install-dependencies-${KERNEL}

echo "================ Build ================"
# Build it...
WITH_ARC="${WITH_ARC}" ./tools-scripts/build-${KERNEL}

# Post installation
echo "================ Post Installation ================"
./tools-scripts/post-install-${KERNEL}

echo "Done..."
