#!/bin/sh

echo "Install GNUstep"
echo " "
cat <<EOF
                    @@@@@@@@@                     
               @@@@@@@@@@@@@@@@@@@                
            @@@@@@@@@@@@@@@@@@@@@@@@@             
          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@          
         @@@@@@@@@@@@@@@@@@@@@@@         @@@@@    
       @@@@@@@@@@@@@@@@@@@@@@@@@          @@@@    
      @@@@@@@@@@@@@@@@@@@@@@@@@@           @@@    
     @@@@@@@@@@@@@@@@@@@@@@@@@@@            @@    
     @@@@@@@@@@@@@@@@@@@@@@@@@@@             @    
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@             @    
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@                  
    @@@@@@@@@@@@@@                                
    @@@@@@@@@@@@@@                                
     @@@@@@@@@@@@@                           @    
     @@@@@@@@@@@@@                           @    
      @@@@@@@@@@@@                          @@    
      @@@@@@@@@@@@                         @@@    
       @@@@@@@@@@@                        @@@@    
         @@@@@@@@@                       @@@@@    
    @@@@@@@                            @@@@@@@    
    @@@@@@@@@                        @@@@@@@@@    
    @@@@@@@@@@@@                  @@@@@@@@@@@@    
    @@@@@@@@@@@@@@@@@@      @@@@@@@@@@@@@@@@@@    
EOF

echo " "
echo "IMPORTANT!"
echo "You must update your .ssh directory so it contains your github ssh key"
echo " "
export KERNEL=`uname -s | sed "s/\-.*//g" | awk '{print(tolower($0))}'`
echo "Begin setup for ${KERNEL}"

if [ ! -f ./setup-${KERNEL} ] ; then
  # Download the setup script only if not already present (e.g. CI).
  export USER=`whoami`
  if [ "X${KERNEL}" == "Xopenbsd" ];then
    ftp -o ./setup-${KERNEL} https://raw.githubusercontent.com/gnustep/tools-scripts/master/setup-${KERNEL}
  else
    curl -fsSL > ./setup-${KERNEL} https://raw.githubusercontent.com/gnustep/tools-scripts/master/setup-${KERNEL}
  fi
  ./setup-${KERNEL}
  rm ./setup-${KERNEL}
else
  # Else, assume inside CI.
  # For CI purposes, default to failing. Using bashism is fine here, for now.
  set -euo pipefail
  ./setup-${KERNEL}
fi

echo "======== Create gnustep build directories ========"
if [ ! -e .git ] ; then
  # Default outside CI.
  mkdir -p gnustep
  cd gnustep
  git clone git@github.com:gnustep/tools-scripts.git
else
  # Inside CI we are already in the repo.
  # Just go to the parent directory, tools-scripts will exist.
  cd ..
fi
./tools-scripts/clone-all-repos

echo "================ Install Dependencies ================"
# Install dependencies
./tools-scripts/install-dependencies-${KERNEL}

echo "================ Build ================"
# Build it...
WITH_ARC="${WITH_ARC}" ./tools-scripts/build-${KERNEL}

# Post installation
echo "================ Post Installation ================"
./tools-scripts/post-install-${KERNEL}

echo "Done..."
