#! /bin/sh
echo "Install dependencies at MSYS2/MINGW64..."

echo "0) Source Version Control"
pacman --noconfirm -S subversion
pacman --noconfirm -S git
pacman --noconfirm -S vim
pacman --noconfirm -S nano

echo "1) gnustep-make dependencies"
pacman --noconfirm -S tar
pacman --noconfirm -S unzip
pacman --noconfirm -S make
pacman --noconfirm -S autogen automake autoconf autoconf2.13 libtool 
pacman --noconfirm -S mingw-w64-x86_64-libtool
pacman --noconfirm -S mingw-w64-x86_64-toolchain
# pacman --noconfirm -S mingw-w64-x86_64-pkg-config
pacman --noconfirm -S mingw-w64-x86_64-cmake
pacman --noconfitm -S base-devel

echo "2) gnustep-base dependencies"
#pacman --noconfirm -S mingw-w64-x86_64-libffi
pacman --noconfirm -S mingw-w64-x86_64-libxml2
pacman --noconfirm -S mingw-w64-x86_64-gnutls
pacman --noconfirm -S mingw-w64-x86_64-libxslt

echo "3) gnustep-gui dependencies"
pacman --noconfirm -S mingw-w64-x86_64-libjpeg-turbo
pacman --noconfirm -S mingw-w64-x86_64-libtiff
pacman --noconfirm -S mingw-w64-x86_64-giflib
pacman --noconfirm -S mingw-w64-x86_64-icu
pacman --noconfirm -S mingw-w64-x86_64-libsndfile
pacman --noconfirm -S mingw-w64-x86_64-aspell
pacman --noconfirm -S mingw-w64-x86_64-lcms mingw-w64-x86_64-lcms2
pacman --noconfirm -S mingw-w64-x86_64-sqlite3
pacman --noconfirm -S mingw-w64-x86_64-windows-default-manifest 

echo "4) gnustep-back dependencies"
pacman --noconfirm -S mingw-w64-x86_64-cairo

echo "5) compiler, also install older binutils to avoid linking issue"
pacman --noconfirm -S mingw-w64-x86_64-clang
pacman --noconfirm -S mingw-w64-x86_64-gcc
pacman --noconfirm -S mingw-w64-x86_64-gcc-objc

#
# IMPORTANT: if you are using the GNUstep release or latest tarballs
# you must uncomment the command below since there will be a link error when
# building libs-base.
#
# pacman --noconfirm -U ./tools-scripts/Packages/mingw-w64-x86_64-binutils-2.34-3-any.pkg.tar.zst

echo "6) tools building libobjc2"
pacman --noconfirm -S ninja
pacman --noconfirm -S asciidoc
pacman --noconfirm -S mingw-w64-x86_64-lld

echo "Done."
# echo "Don't forget to run /mingw64_shell.bat to create a session to build in."
