#! /bin/sh
echo "Install dependencies at MSYS2/MINGW64..."

echo "0) Source Version Control"
pacman --noconfirm -S subversion
pacman --noconfirm -S git

echo "1) gnustep-make"
pacman --noconfirm -S tar
pacman --noconfirm -S unzip
pacman --noconfirm -S make
pacman --noconfirm -S autogen automake autoconf autoconf2.13 libtool mingw-w64-x86_64-libtool
pacman --noconfirm -S mingw-w64-x86_64-toolchain
pacman --noconfirm -S mingw-w64-x86_64-pkg-config

echo "2) gnustep-base"
#pacman --noconfirm -S mingw-w64-x86_64-libffi
pacman --noconfirm -S mingw-w64-x86_64-libxml2
pacman --noconfirm -S mingw-w64-x86_64-gnutls
pacman --noconfirm -S mingw-w64-x86_64-libxslt

echo "3) gnustep-gui"
pacman --noconfirm -S mingw-w64-x86_64-libjpeg-turbo
pacman --noconfirm -S mingw-w64-x86_64-libtiff
pacman --noconfirm -S mingw-w64-x86_64-giflib
pacman --noconfirm -S mingw-w64-x86_64-icu
pacman --noconfirm -S mingw-w64-x86_64-libsndfile
pacman --noconfirm -S mingw-w64-x86_64-aspell
pacman --noconfirm -S mingw-w64-x86_64-lcms mingw-w64-x86_64-lcms2
pacman --noconfirm -S mingw-w64-x86_64-sqlite3

pacman --noconfirm -S asciidoc
pacman --noconfirm -S mingw-w64-x86_64-windows-default-manifest 

echo "4) gnustep-back"
pacman --noconfirm -S mingw-w64-x86_64-cairo

echo "5) compiler"
pacman -S mingw-w64-x86_64-clang
pacman -S mingw-w64-x86_64-gcc
pacman -S mingw-w64-x86_64-gcc-objc

echo "6) ninja"
pacman --noconfirm -S ninja

echo "Done."
echo "Don't forget to run /mingw64_shell.bat to create a session to build in."
