#!/bin/sh

# Inform the user. ;) 
echo "NOTE: Make sure you have done brew update and brew upgrade prior to running this script."
echo "Installing macOS dependencies"
echo "-------"

# Install homebrew...
if [ -e /usr/local/bin/brew ]; then
	echo "Homebrew installed... continuing."
else
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Create frameworks dir...
if [ -e /usr/local/Frameworks ]; then
	echo "Frameworks directory present."
else
	sudo mkdir /usr/local/Frameworks
fi 

# Install dependencies...
echo "-------"
brew install gcc
brew install jpeg 
brew install libtiff 
brew install libpng
brew install libicns 
brew install libxml2
brew install libxslt
brew install gnutls
brew install libffi
# brew install libicu # optional
brew install cairo
# brew install libxft  # provided by X11
# brew install libavahi-client-dev  # optional
# brew install flite-dev # optional
# brew install libxt-dev  # provided by X11
brew install portaudio
brew install make
brew install cmake
# brew install libcurl

#echo "------- Upgrade existing packages..."
#brew upgrade
#echo "-------"
#echo "Done..."

exit 0
