#!/bin/sh

set -e

SCRIPT_DIR=$(CDPATH= cd "$(dirname "$0")" && pwd)
WORKSPACE_DIR=$(CDPATH= cd "${SCRIPT_DIR}/.." && pwd)

wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh 18
sudo apt install clang-18 clangd-18 lld-18 lldb-18 liblldb-18

cd "$WORKSPACE_DIR"

./tools-scripts/build-gnustep --https --clone essential setup clone dependencies
./tools-scripts/clang-build clang-18 clang++-18 ld.lld-18
./tools-scripts/build-gnustep --clone none apps post-install

echo "Done..."
