#!/bin/sh

echo "Installing OpenBSD dependencies"
echo "NOTE: This file assumes that Xorg is installed and that sudo is installed."
echo "      Also, the user must have sudo access to properly execute this script."
echo "Installing..."
sudo pkg_add gmake
sudo pkg_add cmake
sudo pkg_add windowmaker
sudo pkg_add jpeg
sudo pkg_add tiff
sudo pkg_add png
sudo pkg_add libxml
sudo pkg_add libxslt
sudo pkg_add gnutls
sudo pkg_add libffi
sudo pkg_add icu
sudo pkg_add cairo
sudo pkg_add avahi
sudo pkg_add gcc
sudo pkg_add gobjc
sudo pkg_add gdb
sudo pkg_add gnustep-libobjc2
sudo pkg_add flite
echo "Done..."
exit 0
