#! /bin/sh
echo "Install dependencies at MSYS2/MINGW32..."

echo "0) Source Version Control"
pacman -S subversion
pacman -S git

echo "1) gnustep-make"
pacman -S tar
pacman -S unzip
pacman -S make 
pacman -S autogen automake autoconf autoconf2.13 libtool mingw-w64-i686-libtool
pacman -S mingw-w64-i686-toolchain
pacman -S mingw-w64-i686-pkg-config

echo "2) gnutep-base"
#pacman -S mingw-w64-i686-libffi
pacman -S mingw-w64-i686-libxml2
pacman -S mingw-w64-i686-gnutls
pacman -S mingw-w64-i686-libxslt

echo "3) gnustep-gui"
pacman -S mingw-w64-i686-libjpeg-turbo
pacman -S mingw-w64-i686-libtiff
pacman -S mingw-w64-i686-giflib
pacman -S mingw-w64-i686-icu
pacman -S mingw-w64-i686-libsndfile
pacman -S mingw-w64-i686-aspell
pacman -S mingw-w64-i686-lcms mingw-w64-i686-lcms2
pacman -S mingw-w64-i686-sqlite3

pacman -S asciidoc
pacman -S mingw-w64-i686-windows-default-manifest 

echo "4) gnustep-back"
pacman -S mingw-w64-i686-cairo

echo "Done."

