#!/bin/sh
export DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/10.2.0/lib/gcc/10:${DYLD_LIBRARY_PATH}
export LD_LIBRARY_PATH=/usr/local/Cellar/gcc/10.2.0/lib/gcc/10:${LD_LIBRARY_PATH}
echo ${DYLD_LIBRARY_PATH}
