#!/bin/sh

export USER=`whoami`
if [ ! -e /usr/bin/sudo ]; then
   echo "Installing sudo..." 
   if [ -e /usr/bin/apt ]; then
      su -c "apt install sudo"
   else
      su -c "rpm install sudo"
   fi
else
   echo "sudo command is already present."
fi

if [ ! -e /etc/sudoers.d/${USER} ]; then
   echo "Adding ${USER} to sudoers..."
   echo "Please enter the root user's password."
   su -c 'echo "${USER}    ALL=(ALL:ALL) ALL" > /etc/sudoers.d/${USER}'
else
   echo "${USER} is already a member of sudo users."
fi