#!/bin/sh
echo "=== Setup FreeBSD"

# export USER=`whoami`
if [ ! -e /usr/local/bin/sudo ]; then
    echo "Installing sudo"
    echo "Enter root password"
    su -m root -c  'pkg install sudo'
fi

if [ ! -e /usr/local/etc/sudoers.d/${USER} ]; then
    echo "Add ${USER} to sudoers"
    echo "Enter root password"
    su -m root -c 'echo "${USER}    ALL=(ALL:ALL) ALL" > /usr/local/etc/sudoers.d/${USER}'
fi

# Make sure git is installed
if [ ! -e /usr/local/bin/git ]; then
    echo "Enter password for ${USER}"
    sudo pkg install git
fi

if [ ! -e /usr/local/bin/git ]; then
    echo "Enter password for ${USER}"
    sudo pkg install subversion
fi

# done
echo "=== Done"
