#!/bin/sh
echo "=== Setup Haiku"

# Make sure git is installed
if [ ! -e /bin/git ]; then
    pkgman install git
fi

if [ ! -e /bin/svn ]; then
    pkgman install subversion
fi

if [ ! -e /bin/bash ]; then
    pkgman install bash
fi

# done
echo "=== Done"
