#!/bin/sh

set -e

SCRIPT_DIR=$(CDPATH= cd "$(dirname "$0")" && pwd)
WORKSPACE_DIR=$(CDPATH= cd "${SCRIPT_DIR}/.." && pwd)
COMPILER=${1:-clang}
CXX=${2:-clang++}

cd "$WORKSPACE_DIR"

./tools-scripts/build-gnustep --clone all clone

if [ "$COMPILER" = gcc ]; then
    ./tools-scripts/compile-all /usr/GNUstep gcc g++
else
    ./tools-scripts/clang-build "$COMPILER" "$CXX"
fi

make_services
