#!/bin/bash
COMPILER=${1:-clang}
CXX=${2:-clang++}

./tools-scripts/clone-all-repos
if [ "${COMPILER}" != "gcc" ]; then
#    CXX=`echo ${COMPILER} | sed 's/clang/clang++/g`
    ./tools-scripts/clang-build "${COMPILER}" "${CXX}"
else
    ./tools-scripts/compile-all "/usr/GNUstep" "gcc" "g++"
fi
make_services

exit 0
