#!/bin/sh

# GNUSTEP_MSYS=${MSYSTEM,,}/../

GNUSTEP_MSYS=/c/GNUstep
echo "Installation directory is $GNUSTEP_MSYS"
echo "Building for Windows/win32/MinGW..."
echo ""

if [ -f $GNUSTEP_MSYS/lib/pkgconfig/fontconfig.pc ]; then
    echo "fontconfig.pc file exists..."
else
    echo "fontconfig.pc does not exist, copying..."
    mkdir -p /c/GNUstep/lib
    cp ./tools-scripts/fontconfig.pc ${GNUSTEP_MSYS}/lib/pkgconfig
fi

# Set environment vars....
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:${GNUSTEP_MSYS}/lib/pkgconfig:${PKG_CONFIG_PATH}
CFLAGS+=-I/usr/local/include 
LDFLAGS+=-L/usr/local/lib 

export CFLAGS
export LDFLAGS

# Build make
cd tools-make
./configure --with-layout=gnustep --prefix=${GNUSTEP_MSYS}/GNUstep && make install
source ${GNUSTEP_MSYS}/GNUstep/System/Library/Makefiles/GNUstep.sh

# Build base
cd ../libs-base
make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM distclean
./configure --with-installation-domain=SYSTEM --disable-libdispatch --disable-icu && make -j4 GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install

# Build gui
cd ../libs-gui
make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM distclean
./configure && make -j4 GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install

# Build backend
cd ../libs-back
make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM distclean
./configure --enable-graphics=cairo --with-name=cairo && make -j4 GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install 

echo ""
echo "Done."

exit 0
