#!/bin/sh

# GNUSTEP_MSYS=${MSYSTEM,,}/../

GNUSTEP_MSYS=/c/GNUstep
echo "Installation directory is $GNUSTEP_MSYS"
echo "Building for Windows/win32/MinGW..."
echo ""

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:${GNUSTEP_MSYS}/lib/pkgconfig:${PKG_CONFIG_PATH}

# Build make
cd tools-make
./configure --with-layout=gnustep --prefix=${GNUSTEP_MSYS}/GNUstep --enable-install-ld-so-conf && make install messages=yes
source ${GNUSTEP_MSYS}/GNUstep/System/Library/Makefiles/GNUstep.sh

# Build base
cd ../libs-base
make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM distclean
CFLAGS+=-I/usr/local/include LDFLAGS+=-L/usr/local/lib ./configure --with-installation-domain=SYSTEM --disable-libdispatch --disable-icu && make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install messages=yes

# Build gui
cd ../libs-gui
make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM distclean
./configure && make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install messages=yes

# Build backend
cd ../libs-back
make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM distclean
./configure --enable-graphics=cairo --with-name=cairo && make GNUSTEP_INSTALLATION_DOMAIN=SYSTEM debug=yes install messages=yes

echo ""
echo "Done."

exit 0
