#!/bin/sh

PATH=/usr/local/bin:${PATH}
export PATH

REVISION=$1

# Create development...
if [ -e ~/Development ]; then
    cd ~/Development
else
    mkdir ~/Development
fi

# Update llvm...
cd ~/Development
if [ -e llvm-project ]; then
    echo "Updating project"
else
    echo "Cloning project"
    git clone https://github.com/llvm/llvm-project.git
fi
cd llvm-project

# Make the build directory...
rm -rf build
mkdir -p build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/opt/local -DLLVM_ENABLE_PROJECTS=clang -DLLVM_USE_LINKER=gold -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../llvm
cmake --build .
sudo cmake install
