#!/bin/sh

export CC=clang
export CXX=clang++
export MAKE=make

ROOT=~/
USR_ROOT=${ROOT}
GNUSTEP_ROOT=${USR_ROOT}GNUstep
export GNUSTEP_CONFIG_FILE=/etc/GNUstep/GNUstep.conf
export GNUSTEP_INSTALL_LD_SO_CONF=no

echo ""
echo "Installation directory is $GNUSTEP_ROOT"
echo "Building GNUstep for Haiku"
echo ""

# Build make
echo "======== Build make"
cd tools-make
./configure --with-library-combo=ng-gnu-gnu --with-layout=gnustep --prefix=${GNUSTEP_ROOT}
${MAKE}
${MAKE} install
. ${GNUSTEP_ROOT}/System/Library/Makefiles/GNUstep.sh
echo "======== Done"

# Build libjobc2
echo "======== Build libobjc2"
cd ../libobjc2 && [ -d Build ] && rm -rf Build && mkdir Build && cd Build && cmake .. \
-DGNUSTEP_INSTALL_TYPE=SYSTEM \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_CXX_COMPILER=clang++; \
${MAKE} install
echo "======== Done"

# Build base
echo "======== Build base"
cd ../../libs-base
./configure --with-installation-domain=SYSTEM --disable-icu --disable-iconv --disable-invocations
LDFLAGS=${LDFLAGS} CC=${CC} CXX=${CXX} ${MAKE} debug=yes messages=no -j4
./install.sh ${GNUSTEP_ROOT} ${MAKE}
echo "======== Done"

echo "Done."

exit 0
