#!/bin/sh

export CC=clang
export CXX=clang++
export MAKE=gmake
export SUDO=sudo
# export LDFLAGS=-fuse-ld=gold

ROOT=/ 
USR_ROOT=${ROOT}usr
GNUSTEP_ROOT=${USR_ROOT}/GNUstep
export GNUSTEP_CONFIG_FILE=/etc/GNUstep/GNUstep.conf
export GNUSTEP_INSTALL_LD_SO_CONF=no

echo ""
echo "Installation directory is $GNUSTEP_ROOT"
echo "Building GNUstep for FreeBSD"
echo ""

# Build make
echo "======== Build make"
cd tools-make
./configure --with-library-combo=ng-gnu-gnu --with-layout=gnustep --prefix=${GNUSTEP_ROOT}
${MAKE}
${SUDO} -u root ${MAKE} install
. ${GNUSTEP_ROOT}/System/Library/Makefiles/GNUstep.sh
echo "==="

# Build base
echo "======== Build base"
cd ../libs-base
./configure --with-installation-domain=SYSTEM --disable-icu --disable-invocations
LDFLAGS=${LDFLAGS} CC=${CC} CXX=${CXX} ${MAKE} debug=yes messages=no -j4
${SUDO} -u root ./install.sh ${GNUSTEP_ROOT} ${MAKE}
echo "==="

# Build gui
echo "======== Build gui"
cd ../libs-gui
./configure
LDFLAGS=${LDFLAGS} CC=${CC} CXX=${CXX} ${MAKE} debug=yes messages=no -j4
${SUDO} -u root ./install.sh ${GNUSTEP_ROOT} ${MAKE}
echo "==="

# Build backend
echo "======== Build back"
cd ../libs-back
./configure --enable-graphics=cairo
LDFLAGS=${LDFLAGS} CC=${CC} CXX=${CXX} ${MAKE} debug=yes messages=no -j4
${SUDO} -u root ./install.sh ${GNUSTEP_ROOT} ${MAKE}
echo "==="

# Set default backend
# defaults write NSGlobalDomain GSBackend libgnustep-cairo

echo "Done."

exit 0
